config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'welcome/index'
  root 'welcome#index'
  get 'blog/new'
  devise_for :users
  resources :blogs
 	resources :blogs do
  	resources :comments do

  		resources :replies
		end
	end
  post '/likes' => 'likes#create', as: :like_create
 post '/dislikes' => 'likes#dislike', as: :dislike_create




  resources :comments, only: [:index, :new, :create]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
mount_uploader :image, ImageUploader

	  has_many :comments, dependent: :destroy

	  validates :description, presence: true,
	                    length: { minimum: 5 }

	  validates :title, presence: true,
	                    length: { minimum: 3 }
	                    def self.search(search)
  where("title LIKE ?", "%#{search}%") 
end     
	  

end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  has_many :replies
	has_many :likes, as: :likeable, dependent: :destroy
  
end

app/models/like.rb
 class Like < ActiveRecord::Base
 belongs_to :likeable, polymorphic: true
 def self.create_like(comment, current_user)
 like = Like.find_or_initialize_by(:likeable=>comment,:user_id=>current_user.id)
 if like.like
 like.destroy
 else
 like.like= true
 like.save
 end
 end
 def self.create_dislike(comment, current_user)
 like = Like.find_or_initialize_by(:likeable=>comment,:user_id=>current_user.id)
 if like.like==false
 like.destroy
 else
 like.like= false
 like.save
 end
 end
 end

app/models/reply.rb
class Reply < ApplicationRecord
	belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  def is_liked(comment)
 if Like.where(:likeable => comment ,:user_id => self.id).present?
 Like.where(:likeable => comment ,:user_id => self.id).last.like==true
 end
 end
 def is_disliked(comment)
 if Like.where(:likeable => comment ,:user_id => self.id).present?
 Like.where(:likeable => comment ,:user_id => self.id).last.like==false
 end
 end
 def self.find_comment(id, type)
 comment= type.constantize.find(id)
 return comment
 end
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#before_action :authenticate_user!
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index    
    @blogs = Blog.all
  if params[:search]
    @blogs = Blog.search(params[:search]).order("created_at DESC")
  else
    @blogs = Blog.all.order("created_at DESC")
  end
  end
 
  def show
    @blog = Blog.find(params[:id])
  end
 
  def new
    @blog = Blog.new
  end
 
  def edit
    @blog = Blog.find(params[:id])
  end
 
  def create
    params[:blog][:title] = "#{params[:blog][:country_code]}#{params[:blog][:title]}"
    @blog = Blog.new(blog_params)
 
    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end
 
  def update
    @blog = Blog.find(params[:id])
 
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render 'edit'
    end
  end
 
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
 
    redirect_to blogs_path
  end


 
	private
  def blog_params
    params.require(:blog).permit(:title, :category, :image, :description)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def new
    @comment = Comment.new(:blog_id => params[:blog_id])
  end
 
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end
  
 def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :set_comment
 def create
 Like.create_like(@comment, current_user)
 end
 def dislike
 Like.create_dislike(@comment, current_user)
 end
 def set_comment
 @comment=User.find_comment(params[:id], params[:type])
 end
 end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action do
    @comment = Comment.find(params[:comment_id])
    @blog    = Blog.find(params[:blog_id])
  end

  def index
   @replies = @comment.replies
   @reply = @comment.replies.new
  end


  def new
    @reply = @comment.replies.new
  end

  def create
    @reply =  Reply.new(:body=>params[:reply][:body],:comment_id=>params[:reply][:comment_id])
    @reply.save
    flash[:notice]= "replies created"
    redirect_to "/blogs/#{params[:blog_id]}"
  end

  def show
    
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
 module ApplicationHelper
 def count_like(comment)
 comment.likes.where(like: true).count
 end
 def count_dislike(comment)
 comment.likes.where(like: false).count
 end
 end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/edit.html.erb
<h1>Edit blog</h1>
 
<%= form_with(model: @blog, local: true) do |form| %>
 
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :Category %><br>
    <%= form.select(:category, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select Category') %>
  </p>

  <p>
    <%= form.label :Upload_Image %><br>
    <%= form.file_field :image, size: "150pxx10px", alt: "Edit Entry" %>
  </p>
 
  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description, :cols => 30, :rows => 10 %>
  </p>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--img src="bittern/Pro/blogger/app/assets/images/Blogger_logo.svg.png"/-->
          <%= image_tag("Blogger_logo.svg.png", :alt => "Blogger", :size => "240x80") %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://localhost:3000">Home</a></li>
            <li><a href="http://localhost:3000/blogs">Blogs</a></li>
            <li><a href="http://localhost:3000/blogs/new">Create New Blog</a></li>
            
          <ul class="nav navbar-nav navbar-right">
            <li><a href="blogs/:blog_id">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <h1>Listing Blogs</h1>
     
    <table border="2px" class=".table-condensed">
      <tr>
        <th>Title:</th>
        <th>Category:</th>
        <th>Image:</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
     
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.title %></td>
          <td><%= blog.category %></td>
          <td><%= image_tag blog.image_url(:medium).to_s %> </td>
          <td><%= blog.description %></td>
          <td><%= button_to 'Show', blog_path(blog), :method => 'get' %></td>
           <td><%=button_to 'Edit', edit_blog_path(blog), :method => 'get' %></td>
           <td><%= button_to 'Destroy', blog_path(blog),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
    </table>
    <br>
  <% if @blogs.blank? %>
  <h4>There are no Blogs containing the term <%= params[:search] %>.</h4>
   <% end %>
    <%= button_to 'Create New Blog', new_blog_path, :method => 'get' %>





    

app/views/blogs/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--img src="bittern/Pro/blogger/app/assets/images/Blogger_logo.svg.png"/-->
          <%= image_tag("Blogger_logo.svg.png", :alt => "Blogger", :size => "240x80") %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="http://localhost:3000">Home</a></li>
            <li><a href="http://localhost:3000/blogs">Blogs</a></li>
            <li><a href="http://localhost:3000/blogs/new">Create New Blog</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<h1>Create A New Blog</h1>
<%= form_with scope: :blog, url: blogs_path, local: true do |form| %>
<table class=".table-condensed">
<% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blog.errors.count, "error") %> prohibited
        this blog from being saved:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :phone_number %><br>
    <select name="blog[country_code]">
      <%# You can use name instead of alpha3 it will show you  %>
      <% ISO3166::Country.countries.sort_by(&:name).each do |country| %>
        <option value="+<%= country.country_code%>">
          <%= "+#{country.country_code} #{country.alpha3}" %>
        </option>
      <%end%>
    <%= form.text_field :title %>
    </select>
    <%#= select_tag :country, options_from_collection_for_select(ISO3166::Country.countries.sort_by(&:name), 'country_code', ('alpha3')) %>
  </p>
  <p>
    <%= form.label :Category %><br><br>
    <%= form.select(:category, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select Category') %>
  </p>

  <p>
    <%= form.label :Upload_Image %><br><br>
    <%= form.file_field :image%>
  </p>
 
  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description, :cols => 50, :rows => 5 %>
  </p>
  <p>
    <%= form.submit %>
    <%= image_tag("blog-1.jpg", :alt => "Blog", :size => "300x100") %>
  </p>
  </table>
  <%end%>

app/views/blogs/show.html.erb
<h1>Your Blog Created Sucessfully</h1>

    <p>
      <strong>Title:</strong>
      <%= @blog.try(:title) %>
    </p>

    <p>
      <strong> Category:</strong>
      <% if @blog.category.present? %>
      <%= Category.find(@blog.category).name %>
      <% end %>
    </p>

    <p>
      <strong>Image:</strong>
      <%= image_tag @blog.image_url(:medium).to_s %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @blog.try(:description) %>
    </p>

    <h2>Comments</h2>
    <%= render @blog.comments %>

    <h2>Add a comment:</h2>
    <%= render 'comments/form' %>
    
    

     
    <%= button_to 'Edit', edit_blog_path, :method => 'get' %>
    <%= button_to "Back", blogs_path, :method => 'get' %>

app/views/comments/_comment.html.erb
<table border="2px">
<td>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
  	
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
	</p>


	
	<%= link_to 'Destroy Comment', [comment.blog, comment],
			   method: :delete,
			   data: { confirm: 'Are you sure?' } %> |
			   <%= link_to "Reply", new_blog_comment_reply_path(comment.blog, comment) %> 
	</p>
	<%= render partial: "likes/like", locals: {comment: comment } %>

	<h3> reply a comment</h3>
		<% @replies= Reply.where(:comment_id=> comment.id) %>
		<%@replies.each do |reply|%>
  <p>
  	<strong>Reply:</strong>
  	<%=reply.body%>
  	</p>

<%end%>
<%= render :partial => 'replies/form', locals: { blog:  @blog, comment: comment, reply: comment.replies.new} %>

</td></table>




<%#= render 'replies/form', :comment=> @comment %>

<%# @blog = Blog.find(comment.blog_id)%>
<%#= render 'replies/form', locals: { :comment=> comment, :blog => comment.blog }  %>
 

app/views/comments/_form.html.erb
<%= form_with(model: [ @blog, @blog.comments.build ], local: true) do |form| %>
		<%#= form.hidden_field :blog_id %>  
	<p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
	<p>
		 <%= form.submit %>
	</p>
	

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body bgcolor="pink">
  <table>
  <td>
  
  <div id="user_nav">
  <% if user_signed_in? %> Signed in as 
  <%=current_user.email %>.Not you?
    <%=link_to "Sign out", destroy_user_session_path, :method=> :delete %>
  <%else%>

    <%= link_to "Sign up", new_user_registration_path %>
or <%= link_to "sign in", new_user_session_path %>
  <%end%>
</div>
    <%= yield %>
    </td>
    </table>
     <%= form_tag(blogs_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Blog" %>
    <%= submit_tag "Search", :name => nil %>
    <% end %>
    

    
  </body>
</html>

app/views/likes/_like.html.erb
<div id= "like_<%= comment.class.name %>_<%= comment.id %>"> 
<!--Like-->
(<%=count_like(comment)%>)
<% if current_user.is_liked(comment) %>
<%= link_to "liked", like_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
<%else%>
	<%= link_to "like", like_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
	<%end%>

	<!--dislike-->

(<%= count_dislike(comment)%>)
	<% if current_user.is_disliked(comment) %>
		<%= link_to "Disliked", dislike_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
				<%else%>
				<%= link_to "Dislike", dislike_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
			<%end%>

</div>

app/views/likes/create.js.erb
$("#like_<%= @comment.class.name%>_<%= @comment.id %>").html("<%= j(render partial: 'likes/like', locals: {comment: @comment}) %>")

app/views/likes/dislike.js.erb
$("#like_<%= @comment.class.name%>_<%= @comment.id %>").html("<%= j(render partial: 'likes/like', locals: {comment: @comment}) %>")

app/views/replies/_form.html.erb
<%#=byebug%>
<%= form_for([blog, comment, reply]) do |f| %>

   <%= f.hidden_field :comment_id,  :value=> comment.id %>
   <%= f.text_field :body %>
   <%= f.submit %>
   <%end%>

app/views/replies/new.html.erb
<%= render 'form', blog:  @blog, comment: @comment, reply: @reply %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Index</title>
</head>
<body>


<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--img src="bittern/Pro/blogger/app/assets/images/Blogger_logo.svg.png"/-->
          <%= image_tag("Blogger_logo.svg.png", :alt => "Blogger", :size => "240x80") %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="welcome/index">Home</a></li>
            <li><a href="blogs">Blogs</a></li>
            <li><a href="blogs/new">Create New Blog</a></li>
            
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
  <footer>
 <marquee><h1><i><b> Welcome To The  Blogger.com</b></i></h1></marquee>
</footer>

</body>
</html>
<%#= button_to 'Go To Blog Index', blogs_path, :method => 'get' %><br><br>
<%#= button_to 'Create New Blog', new_blog_path, :method => 'get' %><br><br>